spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.142/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
  redis:
    host: 192.168.3.11
    port: 6379
  #jackson:
  # default-property-inclusion: non_null #全局 去掉 类里面的 null
  freemarker:
    suffix: .ftl
logging:
  pattern:
    console: "%d - %msg%n"
  file:
    name: /Volumes/work/学习/SpringBootCode/log/sell.log

wechat:
  mpAppId: wx354379e10e087598
  mpAppSecret: 0df1c96dbe90d0dd99619a4fa32ab8e1

#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
#  mchId: 1483469312
#  mchKey: 098F6BCD4621D373CADE4E832627B4F6
#  keyPath: /Volumes/work/学习/coding-117/doc/h5.p12
#  notifyUrl: http://david888.natapp1.cc/sell/pay/notify

server:
  servlet:
    context-path: /sell

#  appID
#  wx354379e10e087598
#  appsecret
#  0df1c96dbe90d0dd99619a4fa32ab8e1

#https://open:
#  weixin:
#    qq:
#      com/connect/oauth2/authorize?appid=wx354379e10e087598&redirect_uri=http://david888.natapp1.cc&response_type=code&scope=snsapi_base&state=STATE#wechat_redirec:
# mvn clean package -Dmaven.test.skip=true