spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.101/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
logging:
  pattern:
    console: "%d - %msg%n"
  file:
    name: /Volumes/work/学习/SpringBootCode/log/sell.log
